#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew tap homebrew/homebrew-php
        brew install php71 composer
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S php composer
        fi
        ;;
esac

# global packages
composer global require \
    d11wtq/borus \
    phpunit/phpunit \
    techlivezheng/phpctags
