#!/bin/sh

bspc config border_width    5
bspc config window_gap      11
bspc config top_padding     24
# bspc config bottom_padding  0
# bspc config left_padding    0
# bspc config right_padding   0

bspc config split_ratio          0.50
bspc config gapless_monocle      true
bspc config borderless_monocle   true
bspc config paddingless_monocle  false
bspc config click_to_focus       true


#
# Appearance
#

declare -A COLOR
END=15
for ((i=0;i<=END;i++)); do
    COLOR[$i]=$(xrdb -query | awk "/^\*\.color$i:/ {print \$2}")
done

bspc config normal_border_color  "${COLOR[4]}"
bspc config focused_border_color "${COLOR[0]}"
bspc config active_border_color  "${COLOR[13]}"


#
# Displays
#

bspc monitor primary -d 1/{DESKTOP,WEB,CODE,CHAT,ART,MEDIA,MUSIC}
i=2
for monitor in $(bspc query -M | tail -n +2); do
    bspc monitor $monitor -n "$i" -d $i/{DESKTOP,WEB,CODE,CHAT,MUSIC}
    let i++
done
NMON=$i
unset i


#
# Rules
#

bspc rule -a scratchpad state=floating sticky=on center=on
bspc rule -a Emacs desktop=^3 split_ratio=0.25 state=tiled
bspc rule -a Gimp desktop=^6
bspc rule -a mplayer2 state=floating
bspc rule -a Vlc state=floating
bspc rule -a feh state=floating center=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a love state=floating center=on sticky=on
