#!/usr/bin/env bash

case "$OSTYPE" in
    darwin*)
        brew install offlineimap
        brew install mu --with-emacs
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            pacaur --noedit --needed --noconfirm -S offlineimap mu
        fi
        ;;
esac
