#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew install tmux reattach-to-user-namespace
        ;;
    linux*)
        if [ -f /etc/arch-release ]; then
            sudo pacman --needed --noconfirm -S tmux
        elif [ -f /etc/debian-version ]; then
            sudo apt-get install -y tmux
        fi
        ;;
esac

if [[ -z $SERVER ]]; then
    git-repo() { [[ -d $2 ]] || git clone "https://github.com/$1" "$2"; }

    CWD="$(dirname $0)"
    git-repo tmux-plugins/tpm "$CWD/.tmux/plugins/tpm"
    git-repo jimeh/tmuxifier "$CWD/.tmuxifier"
fi
