#!/bin/bash

command -v nvim >/dev/null && exit

case "$OSTYPE" in
    darwin*)
        brew install make
        brew install --HEAD neovim/neovim/neovim
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S make neovim python-neovim
        elif [[ -f /etc/debian_version ]]; then
            sudo apt-get install -y neovim python3-neovim
        fi
        ;;
esac

if [[ ! -d "$HOME/.vim" ]]; then
    git clone --recursive "hlissner/.vim" "$HOME/.vim"
    cd "$HOME/.vim"
    make install
fi
