#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  case $(_os) in
    macos) brew install go ;;
    arch)  yay --needed --noconfirm -S go ;;
  esac

  update
}

update() {
  go get -u github.com/nsf/gocode
  go get -u github.com/motemen/gore
  go get -u golang.org/x/tools/cmd/guru
  go get -u golang.org/x/tools/cmd/gorename
}

# link() {}

# clean() {}

init "$@"
