#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew install go
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S go
        fi
        ;;
esac
