# modules/desktop/term/ghostty.nix
#
# TODO

{ hey, lib, config, options, pkgs, ... }:

with lib;
with hey.lib;
let cfg = config.modules.desktop.term.ghostty;
in {
  options.modules.desktop.term.ghostty = with types; {
    enable = mkBoolOpt false;
    settings = mkOpt (attrsOf attrs) {};
  };

  config = mkIf cfg.enable {
    user.packages = with pkgs; [
      ghostty
    ];

    # modules.shell.tmux.term = mkForce "ghostty";

    # Most remotes don't have foot's terminfo installed and I can't install it
    # on all of them.
    # programs.ssh.extraConfig = ''
    #   Host *
    #     SetEnv TERM=xterm-256color
    # '';

    home.configFile."ghostty/config".text = ''
      # .config/ghostty/config
      # Auto-generated by NixOS config
      config-file = ${hey.configDir}/ghostty/config
      config-file = ?${config.home.configDir}/ghostty/config.theme
      gtk-custom-css = ?${config.home.configDir}/ghostty/config.css
    '';
  };
}
