#!/bin/bash

case "$OSTYPE" in
    darwin*)
        brew install tmux
        ;;
    linux*)
        if [ -f /etc/arch-release ]; then
            sudo pacman --noconfirm -S tmux
        elif [ -f /etc/debian-version ]; then
            sudo apt-get install -y tmux
        fi
esac
