#!/bin/bash

case "$OSTYPE" in
    darwin*)
        brew install tmux
        ;;
    linux*)
        if [ -f /etc/arch-release ]; then
            sudo pacman --noconfirm -S tmux
        elif [ -f /etc/debian-version ]; then
            sudo apt-get install -y tmux
        fi
esac

git-repo() { [[ -d $2 ]] || git clone "https://github.com/$1" "$2"; }

CWD="$(dirname $0)"
git-repo tmux-plugins/tpm "$CWD/.tmux/plugins/tpm"
git-repo jimeh/tmuxifier "$CWD/.tmuxifier"
