#!/usr/bin/env bash
DOTFILES="$(cd $(dirname "${BASH_SOURCE:-${(%):-%x}}") && pwd -P)"
PREFIX="${PREFIX:-/mnt/etc/nixos}"
HOST=${1:-${HOST:-kuro}}

set -e
if [[ ! -f "$DOTFILES/configuration.$HOST.nix" ]]; then
  >&2 echo "No configuration exists for host '$HOST'"
  exit 2
fi

mkdir -p "$PREFIX"
sudo ln -sf "$DOTFILES/configuration.$HOST.nix" "$PREFIX/configuration.nix"

sudo nix-channel --add https://nixos.org/channels/nixos-19.03 nixos
sudo nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz home-manager
sudo nix-channel --update

sudo nixos-generate-config --root "$PREFIX"
sudo nixos-install --root "$PREFIX" -I "config=$DOTFILES"
