#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew install mpd mpc
        brew install ncmpcpp --with-clock --with-visualizer --with-outputs
        ln -sfv $HOME/.config/mpd/mpd-osx.conf $HOME/.config/mpd/mpd.conf
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S mpd mpc ncmpcpp
        fi
        ln -sfv $HOME/.config/mpd/mpd-linux.conf $HOME/.config/mpd/mpd.conf
        ;;
esac
