#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
    macos)  brew install sbdchd/skim/skim ;;
    arch)   pacaur --needed --noconfirm -S skim ;;
    debian) sudo apt-get install -y skim ;;
  esac
}

# update() {}

# link() {}

# clean() {}

init "$@"
