#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  case $(_os) in
    macos) brew install stack ghc ;;
    # The arch linux + haskell situation is a mess. To ensure haskell packages
    # installed via pacman and ones installed via stack/cabal leave each other
    # alone, we need ghc-static + stack-bin.
    arch) yay --needed --noconfirm -S ghc-static stack-bin ;;
  esac
  stack config set system-ghc --global true
  stack setup
}

update() {
  stack update
}

# link() {}

# clean() {}

init "$@"
