#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  _ensure_repo rbenv/rbenv      $RBENV_ROOT
  _ensure_repo rbenv/ruby-build $RBENV_ROOT/plugins/ruby-build
}

update() {
  if [[ -n $RBENV_ROOT ]]; then
    cd $RBENV_ROOT && git pull
    for ver in $RBENV_ROOT/plugins/*(/N); do
      cd $ver && git pull
    done
  fi
}

link() {
  mklink config/irbrc $IRBRC
  mklink config/pryrc $PRYRC
}

clean() {
  rm -fv $IRBRC $PRYRC
  rmdir -v ${IRBRC%/*} ${PRYRC%/*}
}

init "$@"
