#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  wget -O $XDG_BIN_HOME/glslangValidator https://cvs.khronos.org/svn/repos/ogl/trunk/ecosystem/public/sdk/tools/glslang/Install/Linux/glslangValidator
  case $(_os) in
    macos)
        brew install cmake bear gdb
        echo "Note: gdb requires additional setup on MacOS, see https://sourceware.org/gdb/wiki/BuildingOnDarwin"
        ;;
    arch) yay --needed --noconfirm -S cmake bear gdb ;;
  esac
}

# update() {}

# link() {}

# clean() {}

init "$@"
