#!/bin/bash

# Install homebrew
if ! command -v brew >/dev/null; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew install \
    wget curl tree coreutils bash \
    the_silver_searcher pass keybase ffmpeg \
    neofetch youtube-dl
