#!/usr/bin/env zsh

#
# Displays
#

export MONITOR=$(xrandr -q | grep 'primary' | cut -d' ' -f1)
export MONITORS=( $(xrandr -q | grep ' connected' | cut -d' ' -f1) )
MONITOR=${MONITOR:-${MONITORS[0]}}
# Multiple workspaces for main monitor, but only one for others
bspc monitor $MONITOR -d {1,2,3,4,5}
for mon in ${MONITORS[@]/${MONITOR}}; do
    bspc monitor $mon -d $mon/1
done

if ! pgrep polybar >/dev/null; then
    $XDG_CONFIG_HOME/polybar/run.sh
fi


#
# Aesthetics
#


bspc config split_ratio          0.50
bspc config gapless_monocle      true
bspc config borderless_monocle   true
bspc config paddingless_monocle  true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config remove_disabled_monitors false
bspc config remove_unplugged_monitors true

# bspc config normal_border_color  "$COLOR_0"
# bspc config active_border_color  "$COLOR_0"
# bspc config focused_border_color "$COLOR_0"

bspc config border_width    0
bspc config window_gap      8
bspc config top_padding     0
bspc config bottom_padding  0
bspc config left_padding    0
bspc config right_padding   0

bspc config -m $MONITOR window_gap     22
bspc config -m $MONITOR bottom_padding 36
bspc config -m $MONITOR top_padding    0
bspc config -m $MONITOR left_padding   0
bspc config -m $MONITOR right_padding  0



#
# Rules
#

bspc rule -r '*'

# Floating fixes
bspc rule -a 'Emacs:org*' state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating center=on
bspc rule -a Vlc state=floating monitor=C center=on
bspc rule -a love state=floating center=on sticky=on
bspc rule -a SimpleScreenRecorder state=floating center=on sticky=on
bspc rule -a Pinentry state=floating center=on

# Special apps
bspc rule -a URxvt:urxvt-scratch state=floating sticky=on center=on monitor=C
bspc rule -a URxvt:urxvt-fuzzy state=floating sticky=on center=on monitor=C
bspc rule -a Emacs split_ratio=0.25 border=off state=fullscreen
bspc rule -a Gimp desktop=^6
bspc rule -a feh state=fullscreen
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Chromium monitor=L
bspc rule -a Firefox monitor=L
