#!/bin/bash

case $OSTYPE in
    darwin*)
        brew install mercurial
        ;;
    linux*)
        if [ -f /etc/arch-release ]; then
            sudo pacman --needed --noconfirm -S mercurial
        elif [ -f /etc/debian-version ]; then
            sudo apt-get -y mercurial
        fi
esac
