#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew install editorconfig
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            pacaur --needed --noconfirm -S editorconfig-core-c
        fi
        ;;
esac
