#!/bin/bash

if [[ -z $FORCE ]]; then
    command -v fasd >/dev/null && exit
fi

case "$OSTYPE" in
    darwin*)
        brew install fasd
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            pacaur --needed --noconfirm -S fasd
        elif [[ -f /etc/debian_version ]]; then
            sudo add-apt-repository ppa:aacebedo/fasd
            sudo apt update
            sudo apt install -y fasd
        fi
        ;;
esac
