## modules/editor/vim.nix
#
# When I'm stuck in the terminal or don't have access to Emacs, (neo)vim is my
# go-to. I am a vimmer at heart, after all.

{ hey, lib, config, options, pkgs, ... }:

with lib;
with hey.lib;
let cfg = config.modules.editors.vim;
in {
  options.modules.editors.vim = {
    enable = mkBoolOpt false;
  };

  config = mkIf cfg.enable {
    user.packages = with pkgs; [
      editorconfig-core-c
      neovim

      ## For telescope
      git
      fd
      ripgrep

      ## For nvim-treesitter
      gcc
      tree-sitter

      ## Language servers and formatters
      bash-language-server
      lua-language-server
      stylua

      ## For telescope-fzf-native and LuaSnip to build native bits
      gnumake
    ];

    # Load config/nvim from this repo out of $XDG_CONFIG_HOME/nvim so I don't
    # have to nixos-rebuild to see changes.
    home.configFile."nvim/init.lua".text = ''
      -- Auto-generated by nixos
      local root = "${hey.configDir}/nvim"

      vim.g.dotfiles_nvim = root
      vim.opt.runtimepath:prepend(root)
      vim.opt.runtimepath:append(root .. "/after")

      require("config.lazy")
    '';

    # Seeds for rainbow-delimiters. blend harmonises each hue toward the
    # current scheme, so they stay distinguishable without clashing with it.
    modules.hyprland.theme.colors = {
      rainbow_red    = { color = "#e53935"; blend = true; };
      rainbow_orange = { color = "#fb8c00"; blend = true; };
      rainbow_yellow = { color = "#fdd835"; blend = true; };
      rainbow_green  = { color = "#43a047"; blend = true; };
      rainbow_cyan   = { color = "#00acc1"; blend = true; };
      rainbow_blue   = { color = "#1e88e5"; blend = true; };
      rainbow_violet = { color = "#8e24aa"; blend = true; };
    };

    modules.hyprland.theme.templates.nvim = {
      input_path = "${hey.configDir}/nvim/colors.template.lua";
      output_path = "${config.home.stateDir}/nvim/colors.lua";

      # Reload nvim when the theme changes
      post_hook = ''
        for sock in "''${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"/nvim.*; do
          [ -S "$sock" ] || continue
          ${pkgs.neovim}/bin/nvim --server "$sock" \
            --remote-expr "execute('colorscheme matugen')" >/dev/null 2>&1 || true
        done
      '';
    };

    environment.shellAliases = {
      vim = "nvim";
      v   = "nvim";
    };
  };
}
