## modules/desktop/hyprland.nix
#
# Sets up a hyprland-based desktop environment.

{ hey, heyBin, lib, options, config, pkgs, ... }:

with lib;
with hey.lib;
let cfg = config.modules.desktop.hyprland;
    primaryMonitor = findFirst (x: x.primary) {} cfg.monitors;
in {
  options.modules.desktop.hyprland = with types; {
    enable = mkBoolOpt false;
    extraConfig = mkOpt lines "";
    monitors = mkOpt (listOf (submodule {
      options = {
        output = mkOpt str "";
        mode = mkOpt str "preferred";
        position = mkOpt str "auto";
        scale = mkOpt int 1;
        disabled = mkOpt bool false;
        primary = mkOpt bool false;
      };
    })) [{}];
  };

  config = mkIf cfg.enable {
    modules.desktop.enable = true;

    environment.systemPackages = with pkgs; [
      ## For Hyprland & DMS
      xrandr         # for XWayland windows
      adw-gtk3       # for DMS

      ## For CLIs
      gromit-mpx     # for drawing on the screen
      wlr-randr      # for monitors that hyprctl can't handle
      wf-recorder    # for screencasting
      slurp          # slop
      grim           # screenshot (hyprshot, dms screenshot, etc)
      swappy         # satty/Snappy/sharex
    ];

    environment.sessionVariables = {
      ELECTRON_OZONE_PLATFORM_HINT = "auto";
      NIXOS_OZONE_WL = "1";
      MOZ_ENABLE_WAYLAND = "1";
      QT_QPA_PLATFORMTHEME = "gtk3";
      QT_QPA_PLATFORMTHEME_QT6 = "gtk3";
    };

    programs.hyprland = {
      enable = true;
      withUWSM = true;
      systemd.setPath.enable = true;
    };

    programs.dms-shell = {
      enable = true;
      systemd.enable = true;
      enableSystemMonitoring = true;
      enableDynamicTheming = true;
      quickshell.package = hey.inputs.quickshell.packages."${pkgs.stdenv.hostPlatform.system}".default;
    };

    services.greetd = {
      enable = true;
      settings.default_session = {
        command = "uwsm start -eD Hyprland hyprland.desktop";
        user = config.user.name;
      };
    };

    hey = {
      info = {
        hypr = {
          primaryMonitor = primaryMonitor.output or null;
          monitors = cfg.monitors;
        };
        theme.fonts = {
          mono = "JetBrainsMono Nerd Font";
          sans = "Fira Sans";
        };
      };
      hooks = rec {
        startup."05-startup-sound" = ''
          hey .play-sound startup
        '';
        shutdown."05-shutdown-sound" = ''
          hey .play-sound shutdown
        '';

        # I'm using this instead of exec= lines in hyprland.conf so I can ensure
        # these aren't run at startup and sequentially (i.e. predictable order,
        # since Hyprland's exec= calls are parallelized).
        reload."95-hyprland" = ''
          for i in $(hyprctl instances -j | jq -r '.[].instance'); do
            echo "Hyprland: reloading instance $i"
            hey.do hyprctl -i ''${i//*\//} reload config-only
          done
        '';
      };
    };

    home.configFile = {
      "matugen/templates".source = "${hey.configDir}/matugen/templates";

      "matugen/config.toml".text = ''
        [config]
        version_check = false
        import_json_files = ["${config.home.dataDir}/hey/info.json"]

        [templates.hyprland]
        input_path = "${hey.configDir}/matugen/templates/hyprland.lua"
        output_path = "${config.home.configDir}/hypr/hyprland-colors.lua"

        ${optionalString config.modules.shell.tmux.enable ''
          [templates.tmux]
          input_path = "${hey.configDir}/matugen/templates/tmux.conf"
          output_path = "${config.home.configDir}/tmux/dank-colors.conf"
        ''}
        ${optionalString config.modules.desktop.browsers.librewolf.enable ''
          [templates.librewolf]
          input_path = "${hey.configDir}/matugen/templates/librewolf.css"
          output_path = "${config.home.fakeDir}/.librewolf/hlissner.default/chrome/userChrome.colors.css"
        ''}
        ${optionalString config.modules.desktop.apps.rofi.enable ''
          [templates.rofi]
          input_path = "${hey.configDir}/matugen/templates/rofi.rasi"
          output_path = "${config.home.configDir}/rofi/themes/dank-colors.rasi"
        ''}
        ${optionalString config.modules.desktop.term.foot.enable ''
          [templates.foot]
          input_path = "${hey.configDir}/matugen/templates/foot.ini"
          output_path = "${config.home.configDir}/foot/dank-colors.ini"
        ''}
      '';

      "swappy" = {
        source = "${hey.configDir}/swappy";
        recursive = true;
      };

      "hypr/hooks" = {
        source = "${hey.configDir}/hypr/hooks";
        recursive = true;
      };

      "hypr/hyprland.lua".text = ''
        -- Auto-generated by nixos
        package.path = "${hey.configDir}/hypr/?.lua;" .. package.path

        require("hyprland-pre")
        require("hyprland")
        require("hyprland-post")

        local f = io.open("${hey.configDir}/hypr/hyprland-colors.lua")
        if f ~= nil then
            io.close(f)
        else
            require("hyprland-colors")  -- generated by mutagen
        end
      '';

      "hypr/hyprland-pre.lua".text = ''
        -- config/hypr/hyprland-pre.lua
        -- This was automatically generated by NixOS and my dotfiles

        -- Bootstrap session
        hl.on("hyprland.start", function ()
            hl.exec_cmd("hey hook startup")
            ${optionalString (primaryMonitor ? output) ''
              -- Since wayland doesn't have the concept of a primary monitor,
              -- XWayland windows may start in unpredictable places without a hint.
              hl.exec_cmd("xrandr --output $PRIMARY_MONITOR --primary")
            ''}
        end)
        hl.on("hyprland.shutdown", function ()
            os.execute("hey hook shutdown && sleep 0.1")
        end)

        ${concatStringsSep "\n"
          (map (v: ''
            hl.monitor({
              output = "${v.output}",
              mode = "${v.mode}",
              position = "${v.position}",
              scale = ${toString (v.scale or 1)},
              disabled = ${if v.disabled then "true" else "false"}
            })
          '') cfg.monitors)}

        local primaryMonitor = "${primaryMonitor.output or ""}"
        ${optionalString (primaryMonitor ? output) ''
          hl.config({
            cursor = {
              default_monitor = primaryMonitor,
            },
          })

          hl.workspace_rule({ workspace = 1, monitor = primaryMonitor, default = true, persistent = true })
          for i = 2, 9 do
            hl.workspace_rule({ workspace = i, monitor = primaryMonitor })
          end
        ''}
      '';
      "hypr/hyprland-post.lua".text = cfg.extraConfig;
    };

    user.packages = with pkgs; [
      # (catppuccin-kvantum.override {
      #   variant = "mocha";
      #   accent = "maroon";
      # })
      # (graphite-gtk-theme.override {
      #   themeVariants = [ "pink" ];
      #   colorVariants = [ "dark" ];
      #   # sizeVariants = [ "compact" ];
      #   tweaks = [
      #     "normal"
      #     "rimless"
      #     "darker"
      #   ];
      # })
      (catppuccin-papirus-folders.override {
        flavor = "mocha";
        accent = "maroon";
      })
      catppuccin-cursors.mochaDark
      tela-circle-icon-theme

      (mkLauncherEntry "Toggle night mode" {
        icon = "redshift";
        exec = "dms ipc night toggle";
      })
      (mkLauncherEntry "Color picker: grab RGB at point" {
        icon = "com.github.finefindus.eyedropper";
        exec = "dms color pick --rgb -a";
      })
      (mkLauncherEntry "Color picker: grab HSL at point" {
        icon = "com.github.finefindus.eyedropper";
        exec = "dms color pick --hsl -a";
      })
      (mkLauncherEntry "Color picker: grab hex at point" {
        icon = "com.github.finefindus.eyedropper";
        exec = "dms color pick --hex -a";
      })
    ];
  };
}
