#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew install go
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S go
        fi
        ;;
esac

[[ $SHELL == *zsh ]] && source "$(dirname "$0")/env.zsh"

if [[ -d "$GOPATH" ]]; then
    go get -u github.com/nsf/gocode
    go get -u github.com/motemen/gore
    go get -u golang.org/x/tools/cmd/guru
    go get -u golang.org/x/tools/cmd/gorename
fi
