#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  _ensure_repo cehoffman/luaenv     $LUAENV_ROOT
  _ensure_repo cehoffman/lua-build  $LUAENV_ROOT/plugins/lua-build
  _ensure_repo xpol/luaenv-luarocks $LAUENV_ROOT/plugins/luaenv-luarocks
}

update() {
  if [[ -n $LUAENV_ROOT ]]; then
    cd $LUAENV_ROOT && git pull
    for ver in $LUAENV_ROOT/plugins/*(/); do
      cd $ver && git pull
    done
  fi
}

# link() {}

# clean() {}

init "$@"
