#!/usr/bin/env bash

if [[ ! -d ~/.nvm ]]; then
    git clone https://github.com/creationix/nvm ~/.nvm
    cd $HOME/.nvm && git checkout v0.33.2
    export NVM_DIR="$HOME/.nvm"
    . $HOME/.nvm/nvm.sh

    nvm install node
fi
