#!/usr/bin/env bash

if ! pgrep lemonbar >/dev/null; then
    >&2 echo "Lemonbar isn't running"
    exit 1
fi

CWD=$(dirname $0)
if [[ -t 0 ]]; then
    if (( $# == 0 )); then
        >&2 echo "Usage: panel_update.sh [LEMON_TO_UPDATE]"
        exit 1
    fi

    case $1 in
        :*) LEMON="$CWD/lemons/${1#?}"
            if [[ ! -f $LEMON ]]; then
                >&2 echo "Couldn't find that lemon ($1)"
                exit 2
            fi

            . "$CWD/panel-config"
            pkill -f "[bd]ash .+/lemons/${1#?}"
            "$LEMON" > "$PANEL_FIFO" &
            ;;
        *)  echo "$@" | $0
            ;;
    esac
else
    . $CWD/panel-config
    while read -r line; do
        echo "$line" > "$PANEL_FIFO" &
    done
fi
