#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  _ensure_repo pyenv/pyenv $PYENV_ROOT
}

update() {
  if [[ -n $PYENV_ROOT ]]; then
    cd $PYENV_ROOT && git pull
    for ver in $PYENV_ROOT/plugins/*(/N); do
      cd $ver && git pull
    done
  fi
}

link() {
  mklink config/flake8 $XDG_CONFIG_HOME/
}

clean() {
  rm -fv $XDG_CONFIG_HOME/flake8
  rm -rfv $PYENV_ROOT
}

init "$@"
