#!/usr/bin/env bash

MONITORS=( $(xrandr --listactivemonitors | grep -E '^ [0-9]+:' | cut -d' ' -f6 | sed 's/\n/ /') )
MONITOR="${MONITOR:-${MONITORS[0]}}"

# Only have workspaces for primary monitor
bspc monitor $MONITOR -d {1,2,3,4,5}
for mon in ${MONITORS[@]:1}; do
  bspc monitor $mon -d 0
done

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true


# Rules
bspc rule -r '*'

bspc rule -a 'polybar' layer=above
bspc rule -a Pinentry state=floating center=on
bspc rule -a Emacs split_ratio=0.28 state=tiled
bspc rule -a Firefox split_ratio=0.32
bspc rule -a feh state=fullscreen
bspc rule -a 'Emacs:org*' state=floating
bspc rule -a 'Emacs:scratch' state=floating
bspc rule -a 'Emacs:emacs-everywhere' state=floating sticky=on
bspc rule -a '*:xst-scratch' state=floating sticky=on border=off rectangle=2560x480+0+50 monitor=primary

export MONITOR="$MONITOR"
for file in $XDG_CONFIG_HOME/bspwm/rc.d/*; do
  source "$file"
done
