#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew install vim
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S make vim
        fi
        ;;
esac

if [[ ! -d "$HOME/.vim" ]]; then
    git clone --recursive "https://github.com/hlissner/.vim" "$HOME/.vim"
    cd "$HOME/.vim" && make install
fi
