#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  # Install homebrew
  if ! _is_callable brew; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  brew install \
    wget curl tree coreutils bash gnupg2 \
    the_silver_searcher ripgrep ffmpeg keybase \
    neofetch youtube-dl pinentry-mac

  # pass-otp
  brew install pass oath-toolkit
  if _ensure_repo tadfisher/pass-otp /tmp/pass-otp; then
    cd /tmp/pass-otp
    make install PREFIX=/usr/local
  fi
}

update() {
  if _is_callable brew; then
    brew update && brew upgrade && brew cleanup
  else
    echo-fail "homebrew not detected"
  fi
}

# link() {}

# clean() {}

init "$@"
