#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  _ensure_repo madumlao/phpenv $PHPENV_ROOT
  _ensure_repo php-build/php-build $PHPENV_ROOT/plugins/php-build
  case $(_os) in
    arch) yay --needed --noconfirm -S libmcrypt tidy ;;
    macos) brew install libmcrypt tidy-html5 ;;
  esac
}

update() {
  if [[ -n $PHPENV_ROOT ]]; then
    cd $PHPENV_ROOT && git pull
    for ver in $PHPENV_ROOT/plugins/*(/N); do
      cd $ver && git pull
    done
  fi
}

# link() { }

# clean() { }

init "$@"
