{ hey, lib, config, options, pkgs, ... }:

with lib;
with hey.lib;
let cfg = config.modules.shell.zsh;
in {
  options.modules.shell.zsh = with types; {
    enable = mkBoolOpt false;

    rcInit = mkOpt' lines "" ''
      Zsh lines to be written to $XDG_CONFIG_HOME/zsh/extra.zshrc and sourced by
      $XDG_CONFIG_HOME/zsh/.zshrc
    '';
    envInit = mkOpt' lines "" ''
      Zsh lines to be written to ${config.home.configDir}/zsh/extra.zshenv and
      sourced by $XDG_CONFIG_HOME/zsh/.zshenv
    '';

    rcFiles  = mkOpt (listOf (either str path)) [];
    envFiles = mkOpt (listOf (either str path)) [];
  };

  config = mkIf cfg.enable {
    programs.zsh = {
      enable = true;
      # I init completion myself, because enableGlobalCompInit initializes it
      # too soon, which means commands initialized later in my config won't get
      # completion, and running compinit twice is slow.
      enableCompletion = true;
      enableGlobalCompInit = false;
      # Again. I configure the prompt myself, so disable the default.
      promptInit = "";
      # Respect XDG please!
      histFile = "$XDG_STATE_HOME/zsh/history";
      # Implement these manually (and with caching)
      enableLsColors = false;
    };

    users.defaultUserShell = pkgs.zsh;

    # Some interactive shell utilies I find universally indispensible.
    user.packages = with pkgs; [
      at
      bat      # a better cat
      bc
      dust     # a better du
      eza      # a better ls
      zoxide   # a better (and maintained) fasd
      fd       # a better find
      fzf
      gnumake
      libqalculate  # calculator cli w/ currency conversion
      nix-zsh-completions
      ripgrep  # a better grep
      tokei    # for code statistics
      unar
      zip
      unzip
      vim
    ];

    # Ensure XDG compliance
    environment.variables = {
      ZDOTDIR = "$XDG_CONFIG_HOME/zsh";
      ZPM_DIR = "$XDG_DATA_HOME/zpm";
    };

    # Ensure that ZSH's cache directory exists, lest we have IO errors early on.
    systemd.user.tmpfiles.rules = [
      "d %h/.cache/zsh 750 - - - -"
      "d %h/.local/state/zsh 700 - - - -"
    ];

    home.configFile = {
      "zsh/.zshrc".text = ''
        # This file was autogenerated, do not edit it!
        ${optionalString (pathExists "${hey.configDir}/zsh/.zshrc")
          ''source "${hey.configDir}/zsh/.zshrc"''}

        if [[ $TERM != dumb ]]; then
          # modules.shell.zsh.rcInit
          ${cfg.rcInit}

          # modules.shell.zsh.rcFiles
          ${concatMapStrings (path: "source '${path}'\n  ") cfg.rcFiles}
        fi
      '';

      "zsh/.zshenv".text = ''
        # This file is autogenerated, do not edit it!

        # Be more restrictive with permissions in $HOME; no one has any business
        # reading things that don't belong to them.
        if (( EUID != 0 )); then
          umask 027
        else
          # Be even less permissive if root.
          umask 077
        fi
        ${optionalString (pathExists "${hey.configDir}/zsh/.zshenv")
          ''source "${hey.configDir}/zsh/.zshenv"''}

        # modules.shell.zsh.envInit
        ${cfg.envInit}

        # modules.shell.zsh.envFiles
        ${concatMapStrings (path: "source '${path}'\n") cfg.envFiles}
      '';
    };
  };
}
