#!/bin/bash

PANEL_HEIGHT=24
PANEL_FONT="gohufont:size=11:antialias=false"
ICON_FONT="siji:size=9:antialias=false"

# Colors
FG="#bbc2cf" # 1a6582
BG="#e022252c"
HIGHLIGHT="#00185b75"

COLOR_DEFAULT_FG=$FG
COLOR_DEFAULT_BG=$BG
COLOR_MONITOR_FG="#8dbcdf"
COLOR_MONITOR_BG=$BG
COLOR_FOCUSED_MONITOR_FG="#b1d0e8"
COLOR_FOCUSED_MONITOR_BG=$BG
COLOR_FREE_FG="#155872"
COLOR_FREE_BG=$BG
COLOR_FOCUSED_FREE_FG="#000000"
COLOR_FOCUSED_FREE_BG=$HIGHLIGHT
COLOR_OCCUPIED_FG="#a7a5a5"
COLOR_OCCUPIED_BG=$BG
COLOR_FOCUSED_OCCUPIED_FG="#d6d3d2"
COLOR_FOCUSED_OCCUPIED_BG=$HIGHLIGHT
COLOR_URGENT_FG="#f15d66"
COLOR_URGENT_BG=$BG
COLOR_FOCUSED_URGENT_FG="#501d1f"
COLOR_FOCUSED_URGENT_BG="#d5443e"
COLOR_STATE_FG="#89b09c"
COLOR_STATE_BG=$BG
