#!/bin/bash

PWD=$(dirname $0)

sudo pacman --needed --noconfirm -S git

# Install yaourt
if ! command -v yaourt >/dev/null
then
    TEMP=$(mktemp -d)
    pushd $TEMP
    git clone https://aur.archlinux.org/package-query.git && cd package-query && makepkg -si
    git clone https://aur.archlinux.org/yaourt.git && cd yaourt && makepkg -si
    popd
    rm -rf "$TEMP"
fi

# Install from AUR
aur() {
    if ! command -v $1 >/dev/null
    then
        shift
        yaourt --noconfirm -S ${*:-$1}
    fi
}

pacman="sudo pacman --needed --noconfirm -S"

# Essential X things
$pacman xorg-init xorg-server xorg-xandr xorg-xrdb xorg-xmodmap \
        xorg-fonts-75dpi xorg-xfd xdotool

# For wifi
$pacman wpa_supplicant wpa_actiond dhcpcd netctl dialog

# Window manager
$pacman lightdm lightdm-webkit2-greeter bspwm sxhkd compton

# Essential shell utilities
$pacman wget curl make tmux rsync tree the_silver_searcher bc xsel

# Applications
$pacman rxvt-unicode firefox obs-studio chromium

# Utilities
$pacman feh youtube-dl rofi mpd mpc ncmpcpp redshift
aur git-crypt
aur fasd

# Taskbar
aur lemonbar lemonbar-xft-git siji-git
aur xdo-git
aur clock sutils-git

# Fonts
$pacman ttf-dejavu ttf-inconsolata ttf-liberation ttf-ubuntu-font-family terminus-font
# GTK theme
aur '[[ -d /usr/share/themes/Arc-Dark ]]' gtk-theme-arc

# Install hooks
hookdest=/etc/pacman.d/hooks
for hook in $PWD/pacman-hooks/*.hook
do
    [ -f $hookdest/$(basename "$hook") ] || ln -svf $hook $hookdest/
done

# Install crontab
$pacman cronie
[ -f $PWD/crontab ] && crontab $PWD/crontab
