#!/usr/bin/env dash

. $(dirname $0)/../panel-config

num=$({ checkupdates; cower -u; } | wc -l)
if [ "$num" -gt 0 ]
then
    echo "U%{F${COLOR_2}}$ICON_UPD$num%{F-}"
else
    echo "U%{F${COLOR_DIM}}$ICON_UPD%{F-}"
fi

# vim:set ft=sh:
