#!/usr/bin/env dash

# I expect all volume adjustments to be done through vol.sh (in os/arch/bin), which will
# inform lemonbar of changes, so we only need to intialize volume once here.

. $(dirname $0)/../panel-config

data=$(amixer get Master)
vol=0
if echo "$data" | grep '\[on\]' >/dev/null; then
    vol=$(echo "$data" | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p' | uniq)
    case $vol in
        0)                echo "V${ICON_MUTED}  " ;;
        [1-7]|[1-7][0-9]) echo "V${ICON_SPEAKER_LOW} " ;;
        *)                echo "V${ICON_SPEAKER}" ;;
    esac
else
    echo "V%{F${COLOR_DIM}}${ICON_MUTED}%{F-}"
fi

# vim:set ft=sh:
