#!/usr/bin/env sh
#
# AUTHOR: Henrik Lissner
#
# DATE: Tue Nov 26 2019
#
# DESC: Elvi to search twitter
# elvis: twitter           -- Search twitter
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search twitter (twitter.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if [ -z "$w3_args" ]; then
    w3_browse_url "https://twitter.com"
else
    args="$(w3_url_of_arg $we_args)"
    w3_browse_url "https://twitter.com/search?q=${args}"
fi

