#+title: Harusame
#+date:  February 27, 2022

* Overview
My mobile workstation. Comes with me when I travel somewhere I expect to stay
for more than 6 months. Dual boots Windows (for triple-A gaming) and NixOS (for
everything else), and shares a HDD between them.

** Specs
| CASE  | Be Quiet Pure Base 500 - Black          |
| CPU   | AMD Ryzen 5 5800X 6-core 12-thread      |
| MOBO  | MSI B550 PRO-VDH                        |
| COOL  | Be Quiet Pure Rock 2                    |
| GPU   | ASUS GeForce GTX 1660 Super             |
| RAM   | G.SKILL Ripjaws V Series 32GB (2x 16GB) |
| HDD   | Samsung 970 EVO Plus 1TB NVMe M2        |
| HDD   | WDC WD10 1TB platter drive              |
| HDD   | Intel 80GB SSD                          |
| KBD   | [[https://ergodox-ez.com/][ErgoDox-EZ]] (shared from Udon)           |
| MOUSE | Razer Mamba White Edition               |

* Filesystems
** /dev/nvme0n1: Samsung EVO+ 1TB (nixos, /home) :linux:
#+begin_src sh
parted /dev/nvme0n1 -- mklabel gpt
parted /dev/nvme0n1 -- mkpart ESP fat32 1MiB 512MiB
parted /dev/nvme0n1 -- mkpart primary 512MiB 400GiB
parted /dev/nvme0n1 -- mkpart primary 400GiB 100%
parted /dev/nvme0n1 -- set 1 boot on
mkfs.fat -F32 -n BOOT /dev/nvme0n1p1
mkfs.ext4 -L nixos /dev/nvme0n1p2
mkfs.ext4 -L home /dev/nvme0n1p3
#+END_SRC

** /dev/sda: Intel SSD 80gb (windows) :windows:
This NTFS drive is set up on the Windows side, and is never used on the Linux
side. A label isn't required, but makes it easier to mount if needed:
#+begin_src sh
$ ntfslabel /dev/sda windows
#+end_src

** /dev/sdb: WDC WD10 1TB (games) :windows:linux:
This NTFS drive is set up on the Windows side, and shared with the Linux side
(mostly to share my Steam library). It's dedicated hot-storage for games and
video recordings.

On the Linux side, it only needs a label set:
#+begin_src sh
$ ntfslabel /dev/sdb games
#+end_src

* Displays
I have two 27" displays for this system, a Samsung S27E391H and an MSI MD271PW.

To set them up the first time:
#+begin_src sh :results none
xrandr \
    --dpi 72 \
    --output DP-1 --mode 1920x1080 --rate 75 --pos 0x0 \
    --output HDMI-0 --mode 1920x1080 --rate 60 --pos 1920x0 --primary
# Then reload bspwm
~/.config/bspwm/bspwmrc
#+end_src
