#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

VIM_INSTALL_DIR="$XDG_CONFIG_HOME/vim"

install() {
  case $(_os) in
    macos)  _is_callable vim || brew install vim ;;
    arch)   yay --needed --noconfirm -S vim ;;
    debian) sudo apt-get install -y vim ;;
  esac

  _ensure_repo hlissner/.vim $VIM_INSTALL_DIR && \
    cd $VIM_INSTALL_DIR && \
    make install
}

update() {
  cd $VIM_INSTALL_DIR && make update
}

# link() { }

# clean() { }

init "$@"
