#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew install make vim
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S make vim
        elif [[ -f /etc/debian_version ]]; then
            # TODO
            exit 1
        fi
        ;;
esac

if [[ ! -d "$HOME/.vim" ]]
then
    git clone --recursive "hlissner/.vim" "$HOME/.vim"
    cd "$HOME/.vim"
    make install
fi
