#!/usr/bin/env bash

case "$OSTYPE" in
    darwin*)
        brew tap railwaycat/emacsmacport
        brew install emacs-mac --with-imagemagick --with-modern-icon
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S make emacs
        elif [[ -f /etc/debian_version ]]; then
            sudo apt-get install -y make emacs
        fi
        ;;
esac

if [[ ! -d "$HOME/.emacs.d" ]]; then
    git clone --recursive "hlissner/.emacs.d" "$HOME/.emacs.d"
    cd "$HOME/.emacs.d" && make install
fi
