#!/usr/bin/env bash

case "$OSTYPE" in
    darwin*)
        brew install make cask python
        brew tap railwaycat/emacsmacport
        brew install emacs-mac --with-imagemagick --with-modern-icon --HEAD
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S make emacs
        elif [[ -f /etc/debian_version ]]; then
            sudo apt-get install -y make emacs
        fi

        if [[ ! -d ~/.cask ]]; then
            curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
        fi
esac

if [[ ! -d "$HOME/.emacs.d" ]]; then
    git clone --recursive "hlissner/.emacs.d" "$HOME/.emacs.d"
    cd "$HOME/.emacs.d"
    make install
    make snippets
fi
