#!/bin/bash

case "$OSTYPE" in
    darwin*)
        brew install fzf
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S fzf
        elif [[ -f /etc/debian_version ]]; then
            sudo apt-get install -y fzf
        fi
        ;;
esac
