#!/usr/bin/env bash

case "$OSTYPE" in
    darwin*)
        brew install fzf
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S fzf
        fi
        ;;
esac
