# g = git status
# g ... = git $@
g() { [[ $# = 0 ]] && git status --short . || git $*; }
compdef g=hub

if _is_callable hub; then
  alias git='noglob hub'
else
  alias git='noglob git'
fi

alias gbr='git browse'
alias gi='git init'
alias gf='git fetch'
alias gs='git status'
alias gst='git stash'
alias gsp='git stash pop'
alias gsu='git submodule'
alias grb='git rebase -S --autostash -i'
alias gco='git checkout'
alias gcoo='git checkout --'
alias gc='git commit -S'
alias gca='noglob git commit -S -am'
alias gcm='noglob git commit -S -m'
alias gcma='noglob git commit --amend -S -m'
alias gcf='noglob git commit -S --fixup'
alias gC='git commit'
alias gCm='git commit -m'
alias gCma='git commit --amend -m'
alias gCf='git commit --fixup'
alias gcl='git clone'
alias gcp='git cherry-pick -S'
alias gd='git diff'
alias gp='git push'
alias grp='git rev-parse'
alias gpb='git push origin'
alias gpt='git push --follow-tags'
alias gpl='git pull --rebase -S --autostash'
alias ga='git add'
alias gau='git add -u'
alias gb='git branch'
alias gbo='git orphan'
alias gbd='git branch -D'
alias gbl='git blame'
alias gap='git add --patch'
alias gr='git reset HEAD'
alias gt='git tag --sort=v:refname'
alias gtd='gt -d'
alias gta='gt -a'
alias gl='git log --graph --pretty="format:%C(yellow)%h%Creset %C(red)%G?%Creset%C(green)%d%Creset %s %Cblue(%cr) %C(bold blue)<%aN>%Creset"'
alias gll='git log --pretty="format:%C(yellow)%h%Creset %C(red)%G?%Creset%C(green)%d%Creset %s %Cblue(%cr) %C(bold blue)<%aN>%Creset"'
alias gL='gl --stat'
