#!/bin/bash

# Install homebrew
if ! command -v brew >/dev/null; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    # Installing essentials
    brew install wget curl tree coreutils
    # Essential apps
    brew cask install appcleaner iterm2 imageoptim imagealpha
fi

brew install \
    hub the_silver_searcher pass keybase ffmpeg fasd tmux \
    neofetch youtube-dl
