#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  # case $(_os) in
  #   macos)  brew install weechat ;;
  #   arch)   sudo pacman --needed --noconfirm -S weechat ;;
  #   debian) sudo apt-get install -y weechat ;; # NOTE untested
  # esac
}

# update() {}

link() {
  mkdir -p $XDG_CONFIG_HOME/ssh
  if [[ -d ~/.ssh ]]; then
    mv ~/.ssh/* $XDG_CONFIG_HOME/ssh/
    rm -rf ~/.ssh
  fi
}

# clean() {}

init "$@"
