#!/usr/bin/env zsh

# We'll handle compinit ourselves...
export ZGEN_AUTOLOAD_COMPINIT=0

# NOTE ZGEN_DIR and ZGEN_SOURCE are forward-declared in modules/shell/zsh.nix
# NOTE Zgen is no longer maintained; zgenom is a maintained fork
[ -d "$ZGEN_DIR" ] || git clone https://github.com/jandamm/zgenom "$ZGEN_DIR"
source $ZGEN_SOURCE

if ! zgenom saved; then
  echo "Initializing zgenom"
  rm -f $ZDOTDIR/*.zwc(N)

  zgenom load junegunn/fzf shell

  zgenom load jeffreytse/zsh-vi-mode
  zgenom load zsh-users/zsh-completions src
  zgenom load zsh-users/zsh-history-substring-search
  zgenom load zdharma-continuum/history-search-multi-word
  zgenom load romkatv/powerlevel10k powerlevel10k
  zgenom load hlissner/zsh-autopair autopair.zsh
  zgenom load zdharma-continuum/fast-syntax-highlighting

  zgenom save
  zgenom compile $ZDOTDIR
fi

source $ZDOTDIR/config.zsh
if [[ $TERM != dumb ]]; then
  source $ZDOTDIR/keybinds.zsh
  source $ZDOTDIR/completion.zsh
  source $ZDOTDIR/aliases.zsh

  # Auto-generated by nixos
  _source $ZDOTDIR/extra.zshrc
  # If you have host-local configuration, put it here
  _source $ZDOTDIR/local.zshrc

  ##
  autoload -Uz compinit && compinit -u -d $ZSH_CACHE/zcompdump
  autopair-init
fi
