#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew install emacs --with-modules --with-librsvg --with-imagemagick --with-gnutls --with-cocoa
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S make emacs
        elif [[ -f /etc/debian_version ]]; then
            sudo apt-get install -y make emacs
        fi
        ;;
esac

if [[ ! -d "$HOME/.emacs.d" ]]; then
    git clone --recursive "https://github.com/hlissner/.emacs.d" ~/.emacs.d
    cd ~/.emacs.d && YES=1 make install
fi
