#!/usr/bin/env bash

# Bluetooth
sudo ln -sfv $PWD/services/btkbd.conf /etc/
sudo ln -sfv $PWD/services/btkbd.service /etc/systemd/system/

# Install+start service
sudo systemctl enable bluetooth.service
sudo systemctl start bluetooth.service
sudo systemctl enable btkbd.service
sudo systemctl start btkbd.service

# Turn off FN mode
bash -c 'echo 2 > /sys/module/hid_apple/parameters/fnmode'
