#!/bin/sh

source ~/.dotfiles/zsh/functions

if ! is_mac; then
    echo_r "==> Mac: Aborting. This isn't a mac!"
    exit 1
fi

if [ ! -d /usr/local/Cellar ]; then
    echo_g "==> Mac: Installing homebrew"
    ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"

    echo_g "==> Mac: Done! Don't forget to install the Command Line Tools in XCode"
else
    echo_g "==> Mac: Installing basic brews"
    brew tap homebrew/dupes

    brew install wget curl git
    brew install the_silver_search
    brew install lua --with-completion
    brew install macvim --devel --override-system-vim --with-lua
    # brew install vim --override-system-vi --with-lua --with-perl

    brew tap phinze/homebrew-cask
    brew install brew-cask

    while [ $# -gt 0 ]; do
        case "$1" in
            "--essentials") $BASEDIR/macapps/essentials ;;
            "--home") $BASEDIR/macapps/home ;;
        esac
        shift
    done

    echo_g "==> Mac: Done!"
fi
