#!/usr/bin/env zsh

if ! pkg_exists python; then
    pkg_install python
fi

echo_g "==> Installing plugins"
easy_install pip
easy_install cython
pip install PyOpenGL PyOpenGL_accelerate

# Install sfml
source ~/.dotfiles/install/sfml

# Install v1.3 tag because there are bugs in 1.4 atm
pip install git+git://github.com/Sonkun/python-sfml.git@v1.3
