#!/usr/bin/env zsh

keep_alive

BASEDIR=$(dirname "$0")

echo_g "==> Python: Trying to install Python"
pkg_install python

echo_g "==> Python: Installing plugins"
sudo easy_install pip

while [ $# -gt 0 ]; do
    case "$1" in
        "--opengl") 
            $BASEDIR/py/opengl 
            ;;
        "--sfml") 
            sudo easy_install cython
            $BASEDIR/py/sfml 
            ;;
        "--fabric") 
            pip install Jinja2
            pip install fabtools
            $BASEDIR/py/fabric 
            ;;
    esac
    shift
done

echo_g "==> Python: Done!"
