#!/usr/bin/env zsh

if is_mac; then

    # Get SFML 2.1
    if [ ! -d /Library/Frameworks/SFML.framework ]; then
        echo_g "==> Installing SFML 2.1"

        mkdir ~/.temp-sfml
        cd ~/.temp-sfml

        SFML="SFML-2.1-osx-gcc-universal.tar.gz"

        # wget http://www.sfml-dev.org/download/sfml/2.1/SFML-2.1-osx-clang-universal.tar.gz
        wget http://www.sfml-dev.org/download/sfml/2.1/$SFML
        tar -xvf $SFML
        cd $SFML
        sudo ./install.sh
        rm -rf ~/.temp-sfml

        pip install git+git://github.com/Sonkun/python-sfml.git@v1.3
    else
        echo_r "==> SFML 2.1 already installed"
    fi

elif is_deb; then

    echo_r "==> SFML install script for linux is incomplete!"

fi
