#!/usr/bin/env zsh

if ! command_exists "tmux"; then
    echo_g "==> Installing tmux"
    pkg_install tmux
    if is_mac; then
        brew install reattach-to-user-namespace libevent
    fi
else
    echo_r "==> Tmux is already installed!"
fi

echo_g "==> Tmux: Setting up symlinks"
do_link ~/.dotfiles/tmux.conf ~/.tmux.conf

echo_g "==> DONE!"
