#!/bin/zsh

if ! command-exists brew; then
    echo "Requires homebrew"
    exit
fi

if [ ! `command -v "tmux"` ]; then
    echo "==> Tmux: Installing tmux & reattach-to-user-namespace"
    brew install tmux reattach-to-user-namespace libevent | indent
else
    echo "==> Tmux: already installed!"
fi

echo "==> Tmux: Setting up symlinks"
ln -sf ~/.dotfiles/tmux.conf ~/.tmux.conf

echo "==> Tmux: DONE!"
