#!/bin/zsh

if [ ! `command -v "brew"` ]; then
    echo "Homebrew is required!"
    exit
fi

if [ ! `command -v "mvim"` ]; then
    echo "\n* Installing macvim"
    brew install macvim --with-cscope --override-system-vim
fi

if [ ! -e ~/.vimrc ]; then
    echo "\n* Installing vim rcfiles"

    if [ -d ~/.vim ]; then
        rm -rf ~/.vim
    fi
    sh <(curl https://raw.github.com/hlissner/mlvim/master/install.sh -L)
fi

echo "\n* Updating vim..."
vim +BundleInstall! +BundleClean! +q +q

if [ ! -e ~/.vim/bundle/YouCompleteMe/python/ycm_core.so ]; then
    echo "\n* Trying to compile YCM"
    brew install cmake
    cd ~/.vim/bundle/YouCompleteMe
    ./install.sh --clang-completer
fi

echo "\nDone!"
