#!/usr/bin/env bash

source ~/.dotfiles/zsh/functions

if [ ! -d ~/.oh-my-zsh ]; then
    # Try to install zsh
    if ! pkg_install zsh; then
        echo_g "==> ZSH: Homebrew is not installed!"
        exit 1
    fi

    # https://github.com/robbyrussell/oh-my-zsh
    echo_g "==> ZSH: Installing oh-my-zsh"
    curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
    
    # Set new shell
    echo_g "==> ZSH: Changing shell"
    
    local zsh_bin=$(which zsh)
    if !grep -i "$zsh_bin" /etc/shells; then
        echo_r "==> ZSH: You need to add $zsh_bin to /etc/shells!"
    else
        chsh -s $(which zsh)
    fi

else
    echo_g "==> ZSH: Updating"
    cd ~/.oh-my-zsh
    git pull
fi

# Create links
echo_g "==> ZSH: Setting up symlinks"
do_link ~/.dotfiles/zsh ~/.zsh
do_link ~/.dotfiles/zshrc ~/.zshrc
do_link ~/.dotfiles/zshenv ~/.zshenv
do_link ~/.dotfiles/bashrc ~/.bashrc

echo_g "==> ZSH: DONE!"
