#!/bin/bash

if [ ! -d ~/.oh-my-zsh ]; then
    # https://github.com/robbyrussell/oh-my-zsh
    echo "==> ZSH: Installing oh-my-zsh"
    curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
    
    # Set new shell
    echo "==> ZSH: Changing shell"
    chsh -s /bin/zsh
fi

# Create links
echo "==> ZSH: Setting up symlinks"
[ -d ~/.zsh ] && rm ~/.zsh
ln -sf ~/.dotfiles/zsh ~/.zsh
ln -sf ~/.dotfiles/zshrc ~/.zshrc
ln -sf ~/.dotfiles/zshenv ~/.zshenv
ln -sf ~/.dotfiles/bashrc ~/.bashrc

echo "==> ZSH: DONE!"
