#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case "$OSTYPE" in
    darwin*)
      brew install offlineimap
      brew install mu --with-emacs
      ;;
    linux*)
      if [[ -f /etc/arch-release ]]; then
        yay --needed --noconfirm -S offlineimap mu
      fi
      ;;
  esac
}

#update() {}

link() {}

clean() {}

init "$@"
