#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  _ensure_repo nodenv/nodenv     $NODENV_ROOT
  _ensure_repo nodenv/node-build $NODENV_ROOT/plugins/node-build
}

update() {
  if [[ -n $NODENV_ROOT ]]; then
    cd $NODENV_ROOT && git pull
    for ver in $NODENV_ROOT/plugins/*(/); do
      cd $ver && git pull
    done
  fi
}

# link() {}

# clean() {}

init "$@"
