# modules/apps/term/foot.nix
#
# TODO

{ hey, lib, config, options, pkgs, ... }:

with lib;
with hey.lib;
let cfg = config.modules.apps.term.foot;
in {
  options.modules.apps.term.foot = with types; {
    enable = mkBoolOpt false;
    settings = mkOpt (attrsOf attrs) {};
  };

  config = mkIf cfg.enable {
    user.packages = with pkgs; [
      foot
      libsixel  # image support in foot
    ];

    modules.shell.tmux.term = mkForce "foot";

    # Most remotes don't have foot's terminfo installed and I can't install it
    # on all of them.
    programs.ssh.extraConfig = ''
      Host *
        SetEnv TERM=xterm-256color
    '';

    modules.hyprland.theme.templates.foot = {
      input_path = "${hey.configDir}/foot/colors.template.ini";
      output_path = "${config.home.configDir}/foot/colors.ini";
    };

    home.configFile."foot/foot.ini".text = ''
      # .config/foot/foot.ini
      # Auto-generated by NixOS config
      font=${config.hey.info.theme.fonts.mono or "monospace"}:size=9
      include=${config.home.configDir}/foot/colors.ini
      include=${hey.configDir}/foot/foot.ini
    '';
  };
}
