# modules/apps/term/foot.nix
#
# TODO

{ self, lib, config, options, pkgs, ... }:

with lib;
with self.lib;
let cfg = config.modules.apps.term.foot;
in {
  options.modules.apps.term.foot = with types; {
    enable = mkBoolOpt false;
  };

  config = mkIf cfg.enable {
    user.packages = with pkgs; [
      foot
      libsixel  # image support in foot
    ];

    modules.shell.tmux.term = mkForce "foot";

    # Most remotes don't have foot's terminfo installed and I can't install it
    # on all of them.
    programs.ssh.extraConfig = ''
      Host *
        SetEnv TERM=xterm-256color
    '';

    # Intentionally avoiding noctalia's foot template because it wants to write
    # to foot.ini and has no post_hook reloader. foot can't reload its config,
    # so ours pushes the new palette into live windows as OSC sequences.
    modules.wm.theme.files.foot = {
      input_path = "${config.hey.configDir}/foot/colors.template.ini";
      output_path = "${config.home.configDir}/foot/colors.ini";
      post_hook = "${config.hey.configDir}/foot/bin/reload-colors.zsh";
    };

    home.configFile."foot/foot.ini".text = ''
      # .config/foot/foot.ini
      # Auto-generated by NixOS config
      font=${config.hey.info.theme.fonts.mono or "monospace"}:size=9
      include=${config.home.configDir}/foot/colors.ini
      include=${config.hey.configDir}/foot/foot.ini
    '';
  };
}
