# modules/apps/term/foot.nix
#
# TODO

{ hey, lib, config, options, pkgs, ... }:

with lib;
with hey.lib;
let cfg = config.modules.apps.term.foot;
in {
  options.modules.apps.term.foot = with types; {
    enable = mkBoolOpt false;
  };

  config = mkIf cfg.enable {
    user.packages = with pkgs; [
      foot
      libsixel  # image support in foot
    ];

    modules.shell.tmux.term = mkForce "foot";

    # Most remotes don't have foot's terminfo installed and I can't install it
    # on all of them.
    programs.ssh.extraConfig = ''
      Host *
        SetEnv TERM=xterm-256color
    '';

    # Noctalia tries to write to foot.ini! See
    # https://github.com/noctalia-dev/noctalia/blob/main/assets/templates/foot/apply.sh
    modules.hyprland.theme.builtinTemplates = [ "foot" ];
    home.configLink."foot/foot.ini" = "${hey.configDir}/foot/foot.ini";
    home.configFile."foot/foot.extra.ini".text = ''
      # .config/foot/foot.extra.ini
      # Auto-generated by NixOS config
      font=${config.hey.info.theme.fonts.mono or "monospace"}:size=9
    '';
  };
}
