#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew install vim
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S vim
        elif [[ -f /etc/debian_version ]]; then
            sudo apt-get install -y vim
        fi
        ;;
esac

[[ -f ~/.vimrc ]] || wget -O ~/.vimrc https://raw.githubusercontent.com/hlissner/.vim/master/vimrc.mini
