#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        # TODO
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S rtorrent
            pip install pyrocore
        fi
esac


