#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew cask install firefox
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S firefox
        fi
        ;;
esac
