#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        command -v nvim >/dev/null || brew install --HEAD neovim/neovim/neovim
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S make neovim python-neovim
        elif [[ -f /etc/debian_version ]]; then
            sudo apt-get install -y neovim python3-neovim
        fi
        ;;
esac

if [[ ! -d "$HOME/.vim" ]]; then
    git clone --recursive "https://github.com/hlissner/.vim" "$HOME/.vim"
fi

if [[ -f "$HOME/.vim/Makefile" ]]; then
    cd "$HOME/.vim" && make install && make neovim
fi

