#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  # TODO Install android SDK
  case $(_os) in
    macos) brew cask install java gradle ;;
    arch)  yay --needed --noconfirm -S jdk8-openjdk gradle ;;
  esac
}

# update() {}

# link() {}

# clean() {}

init "$@"
