#!/bin/zsh
# ZSH-specific aliases. Find the rest in ~/.bash/aliases

source ~/.bash/aliases

# GIT
alias ag='nocorrect noglob ag'
alias rk='noglob rake'
alias rkg='noglob rake -g'
alias rename='noglob rename'

export p=~/Dropbox/projects

zman() {
    PAGER="less -g -s '+/^       "$1"'" man zshall
}
