#!/bin/zsh

# Disable autocorrect behavior, very annoying!
# unsetopt correct_all

# Don't wait for keys (snappier vi-mode)
export KEYTIMEOUT=1

zle -N edit-command-line
bindkey -v
bindkey '^f' edit-command-line

bindkey -M viins '^w' backward-kill-word
bindkey -M viins '^a' beginning-of-line
bindkey -M viins '^e' end-of-line
