#!/bin/zsh

# Disable autocorrect behavior, very annoying!
unsetopt correct_all
# Don't wait for keys (snappier vi-mode)
export KEYTIMEOUT=1

zle -N edit-command-line
bindkey -v
bindkey '^f' edit-command-line

bindkey '^w' backward-kill-word
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line
