#!/bin/bash

if [ -d ~/Dropbox ]; then
    PATH=~/Dropbox/dev/bin:$PATH
fi

if [ "`command -v brew 2>&1`" ]; then
    BREWDIR=`brew --prefix`

    PATH=$BREWDIR/sbin:$PATH
    PATH=$BREWDIR/bin:$PATH

    COREUTIL=`brew --prefix coreutils`
    if [ -d "$COREUTIL" ]; then
        PATH=`brew --prefix coreutils`:$PATH
    fi
fi

PATH=$HOME/.rvm/bin:$PATH
