#!/bin/bash

if command-exists brew; then
    BREWDIR=`brew --prefix`

    PATH=$BREWDIR/sbin:$PATH
    PATH=$BREWDIR/bin:$PATH

    COREUTIL=`brew --prefix coreutils`
    if [ -d "$COREUTIL" ]; then
        PATH=`brew --prefix coreutils`:$PATH
    fi
fi

PATH=$HOME/.rvm/bin:$PATH

if [ -d ~/.dotfiles ]; then
    PATH=~/.dotfiles/bin:$PATH
fi
