#!/bin/bash

prompt_pwd() {
    SHORTPWD=`print -Pn "%4~"`
    [[ "${SHORT_PWD:0:1}" =~ "[^/~]" ]] && SHORT_PWD=".../$SHORT_PWD"
    echo -n $SHORTPWD
}

prompt_git() {
    if [ "`git_prompt_info`" ]; then
        echo -n "$(git_prompt_info)"
    fi
}

# GIT Stuff
ZSH_THEME_GIT_PROMPT_PREFIX=" :%{$fg[white]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[red]%}+%{$fg[white]%}"
# ZSH_THEME_GIT_PROMPT_CLEAN=""


##################
#  Build Prompt  #
##################

prompt() {
    echo -n "%{$fg[red]%}"
    echo -n "%{$FX[bold]%}"

    # Show the hostname if this is an SSH session
    if [[ -n $SSH_CLIENT ]]; then
        echo -n "$(hostname) "
    fi

    # The prompt
    echo -n "\$ %{$FX[no-bold]%}"
}

rprompt() {
    # Make the rprompt a bright grey to set it apart
    echo -n "%{$FG[245]%}"
    echo -n '$(prompt_pwd)'

    # Show the branch/status if in a git repo
    echo -n '$(prompt_git)'

    # Reset formatting for command output
    echo -n "%{$reset_color%}"
}

PROMPT="$(prompt)"
RPROMPT="$(rprompt)"
