## modules/hyprland/default.nix
#
# Sets up a hyprland-based desktop environment.

{ hey, heyBin, lib, options, config, pkgs, ... }:

with lib;
with hey.lib;
let cfg = config.modules.hyprland;
    primaryMonitor = findFirst (x: x.primary) {} cfg.monitors;
    iconTheme   = "Dracula";
    cursorTheme = "catppuccin-mocha-dark-cursors";
    cursorSize  = 32;
in {
  options.modules.hyprland = with types; {
    enable = mkBoolOpt false;
    extraConfig = mkOpt lines "";
    monitors = mkOpt (listOf (submodule {
      options = {
        output = mkOpt str "";
        mode = mkOpt str "preferred";
        position = mkOpt str "auto";
        scale = mkOpt int 1;
        disabled = mkOpt bool false;
        primary = mkOpt bool false;
        vrr = mkOpt int 0;
      };
    })) [{}];
  };

  config = mkIf cfg.enable {
    hey.info.hypr = {
      primaryMonitor = primaryMonitor.output or null;
      monitors = cfg.monitors;
    };

    programs.hyprland = {
      enable = true;
      withUWSM = true;
      systemd.setPath.enable = true;
    };

    environment.systemPackages = with pkgs; [
      ## For Hyprland
      xrandr         # for XWayland windows

      ## For CLIs
      gromit-mpx     # for drawing on the screen
      wlr-randr      # for monitors that hyprctl can't handle
      wf-recorder    # for screencasting
      quickshell     # for screencast's region indicator
      slurp          # slop
      grim           # screenshot (hyprshot, dms screenshot, etc)
      swappy         # satty/Snappy/sharex
      ripdrag        # Replaces xdragon
      wev            # Replaces xev
      wl-clipboard   # Replaces xclip
      wtype          # Replaces xdotool (sorta)
      swayimg        # Replaces feh (as an image previewer)
      imv
      libnotify      # notify-send
      xdg-utils
      sox            # for `play` utility

      ## For theme
      catppuccin-cursors.mochaDark
      tela-circle-icon-theme
      dracula-icon-theme
    ];

    fonts = {
      fontDir.enable = true;
      enableGhostscriptFonts = true;
      packages = with pkgs; [
        # For GUIs
        fira
        ubuntu-classic

        # For editors/terminals
        dejavu_fonts
        fira-code
        fira-code-symbols
        symbola
        nerd-fonts.jetbrains-mono

        # For design software
        montserrat
        open-sans
      ];
    };
    hey.info.theme.fonts = {
      mono = "JetBrainsMono Nerd Font";
      sans = "Fira Sans";
    };

    # DMS resolves "System Default" for icons and the cursor by shelling out to
    # gsettings, so the defaults have to live in dconf for it to find them.
    programs.dconf = {
      enable = true;
      profiles.user.databases = [{
        settings."org/gnome/desktop/interface" = {
          icon-theme = iconTheme;
          cursor-theme = cursorTheme;
          cursor-size = gvariant.mkInt32 cursorSize;
        };
      }];
    };

    environment.sessionVariables = {
      ELECTRON_OZONE_PLATFORM_HINT = "auto";
      NIXOS_OZONE_WL = "1";
      MOZ_ENABLE_WAYLAND = "1";
      # nixpkgs ships schemas outside XDG_DATA_DIRS, so gsettings needs pointing.
      GSETTINGS_SCHEMA_DIR = pkgs.glib.getSchemaPath pkgs.gsettings-desktop-schemas;
      XCURSOR_THEME = cursorTheme;
      XCURSOR_SIZE = toString cursorSize;
    };

    modules.hyprland.matugen.templates.hyprland = {
      input_path = "${hey.configDir}/hypr/hyprland-colors.template.lua";
      output_path = "${config.home.configDir}/hypr/hyprland-colors.lua";
    };

    modules.shell.zsh.rcFiles = [ "${hey.configDir}/hypr/aliases.zsh" ];

    home.configFile = {
      "swappy/config".text = ''
        [Default]
        early_exit=true
        save_dir=/run/user/${toString config.user.uid}/swappy/
      '';

      "hypr/hyprland.lua".text = ''
        -- Auto-generated by nixos
        package.path = "${hey.configDir}/hypr/?.lua;" .. package.path

        ${concatStringsSep "\n"
          (map (v: ''
            hl.monitor({
              output = "${v.output}",
              mode = "${v.mode}",
              position = "${v.position}",
              scale = ${toString (v.scale or 1)},
              disabled = ${if v.disabled then "true" else "false"},
              vrr = ${toString (v.vrr or 0)}
            })
          '') cfg.monitors)}

        HOSTNAME = "${config.networking.hostName}"
        ${optionalString (primaryMonitor ? output) ''
          PRIMARY_MONITOR = "${primaryMonitor.output or ""}"
          hl.on("hyprland.start", function ()
              -- Wayland has no concept of a primary monitor, so XWayland
              -- windows may start in unpredictable places without a hint.
              hl.exec_cmd("xrandr --output " .. PRIMARY_MONITOR .. " --primary")
          end)
          hl.config({ cursor = { default_monitor = PRIMARY_MONITOR } })
        ''}

        require("hyprland")
        require("hyprland-post")

        local f = io.open("${hey.configDir}/hypr/hyprland-colors.lua")
        if f ~= nil then
            io.close(f)
        else
            require("hyprland-colors")  -- generated by mutagen
        end
      '';

      "hypr/hyprland-post.lua".text = cfg.extraConfig;
    };
  };
}
