## modules/hyprland/default.nix
#
# Sets up a hyprland-based desktop environment.

{ hey, heyBin, lib, options, config, pkgs, ... }:

with lib;
with hey.lib;
let cfg = config.modules.hyprland;
    primaryMonitor = findFirst (x: x.primary) {} cfg.monitors;
    iconTheme   = "Dracula";
    cursorTheme = "catppuccin-mocha-dark-cursors";
    cursorSize  = 32;
    matugenModule = "hyprland-colors";

    # Describe the `hey` table for `lua-language-server` dynamically, so the two
    # can't drift. Nested classes must come first.
    luaMeta = name: attrs: bind:
      let
        typeOf = path: v:
               if v == null  then "any"  # says a field exists, not what it holds
          else if isBool v   then "boolean"
          else if isInt v    then "integer"
          else if isString v then "string"
          else if isAttrs v  then path
          else if isList v   then (if v == [] then "any[]" else "${typeOf path (head v)}[]")
          else "number";
        # A list documents its element type, so both spell the same class name.
        elemOf = v: if isList v && v != [] then head v else v;
        nested = concatMap
          (n: let path = "${name}.${n}"; in
              optionals (isAttrs (elemOf attrs.${n}))
                (luaMeta path (elemOf attrs.${n})
                         "local ${replaceStrings ["."] ["_"] "__${path}"}"))
          (attrNames attrs);
      in nested ++ [ ''
        ---@class ${name}
        ${concatMapStringsSep "\n"
            (n: "---@field ${n} ${typeOf "${name}.${n}" attrs.${n}}")
            (attrNames attrs)}
        ${bind} = {}
      '' ];

    heyMeta = pkgs.writeText "hey.meta.lua" ''
      -- Auto-generated by nixos, from hey.info. Describes the `hey` table that
      -- modules/hyprland/default.nix splices into hyprland.lua.
      ---@meta

      ${concatStringsSep "\n" (luaMeta "hey" config.hey.info "hey")}
    '';
in {
  options.modules.hyprland = with types; {
    enable = mkBoolOpt false;
    extraConfig = mkOpt lines "";
    monitors = mkOpt (listOf (submodule {
      options = {
        output = mkOpt str "";
        mode = mkOpt str "preferred";
        position = mkOpt str "auto";
        scale = mkOpt int 1;
        disabled = mkOpt bool false;
        primary = mkOpt bool false;
        vrr = mkOpt int 0;
      };
    })) [{}];
  };

  config = mkIf cfg.enable {
    hey.desktop = "hyprland";

    hey.info.hypr = {
      primaryMonitor = primaryMonitor.output or null;
      monitors = cfg.monitors;
    };

    programs.hyprland = {
      enable = true;
      withUWSM = true;
      systemd.setPath.enable = true;
    };

    environment.systemPackages = with pkgs; [
      ## For CLIs
      gromit-mpx     # for drawing on the screen
      wlr-randr      # for monitors that hyprctl can't handle
      wf-recorder    # for screencasting
      quickshell     # for screencast's region indicator
      slurp          # slop
      grim           # screenshot (hyprshot, dms screenshot, etc)
      ripdrag        # Replaces xdragon
      wev            # Replaces xev
      wl-clipboard   # Replaces xclip
      wtype          # Replaces xdotool (sorta)
      swayimg        # Replaces feh (as an image previewer)
      imv
      libnotify      # notify-send
      xdg-utils
      sox            # for `play` utility

      ## For theme
      catppuccin-cursors.mochaDark
      tela-circle-icon-theme
      dracula-icon-theme
    ];

    fonts = {
      fontDir.enable = true;
      enableGhostscriptFonts = true;
      packages = with pkgs; [
        # For GUIs
        fira
        ubuntu-classic

        # For editors/terminals
        dejavu_fonts
        fira-code
        fira-code-symbols
        symbola
        nerd-fonts.jetbrains-mono

        # For design software
        montserrat
        open-sans
      ];
    };
    hey.info.theme.fonts = {
      mono = "JetBrainsMono Nerd Font";
      sans = "Fira Sans";
    };

    # DMS resolves "System Default" for icons and the cursor by shelling out to
    # gsettings, so the defaults have to live in dconf for it to find them.
    programs.dconf = {
      enable = true;
      profiles.user.databases = [{
        settings."org/gnome/desktop/interface" = {
          icon-theme = iconTheme;
          cursor-theme = cursorTheme;
          cursor-size = gvariant.mkInt32 cursorSize;
        };
      }];
    };

    environment.sessionVariables = {
      ELECTRON_OZONE_PLATFORM_HINT = "auto";
      NIXOS_OZONE_WL = "1";
      MOZ_ENABLE_WAYLAND = "1";
      # nixpkgs ships schemas outside XDG_DATA_DIRS, so gsettings needs pointing.
      GSETTINGS_SCHEMA_DIR = pkgs.glib.getSchemaPath pkgs.gsettings-desktop-schemas;
      XCURSOR_THEME = cursorTheme;
      XCURSOR_SIZE = toString cursorSize;
    };

    modules.hyprland.matugen.templates.hyprland = {
      input_path = "${hey.configDir}/hypr/hyprland-colors.template.lua";
      output_path = "${config.home.configDir}/hypr/${matugenModule}.lua";
    };

    modules.shell.zsh.rcFiles = [ "${hey.configDir}/hypr/aliases.zsh" ];

    # Trigger onShutdown hook at the end of graphical-session, so we can have a
    # fade-out transition and shutdown sound.
    systemd.user.services.hey-shutdown-hook = {
      description = "Run hey hook onShutdown before session dies";
      wantedBy = [ "graphical-session.target" ];
      partOf = [ "graphical-session.target" ];
      after = [
        "graphical-session.target"
        "wayland-wm@hyprland.desktop.service"  # the compositor, for the fade
        "dms.service"                          # the toast
        "pipewire.service"                     # the sound; sox goes out
        "pipewire-pulse.service"               # through the pulse shim
      ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = "${getExe' pkgs.coreutils "true"}";
        ExecStop = "${heyBin} hook onShutdown";
        # A wedged hook must not hold the shutdown open indefinitely.
        TimeoutStopSec = 15;
      };
    };

    # So lua-language-server completion and linting is aware of hyprland's API,
    # and of the hey table this module splices in beside it. Both are gitignored
    # by .gitignore's *.meta.lua.
    system.userActivationScripts.hyprlandLuaStub = ''
      ln -sfn ${config.programs.hyprland.package}/share/hypr/stubs/hl.meta.lua \
              ${hey.configDir}/hypr/lib/hl.meta.lua
      ln -sfn ${heyMeta} ${hey.configDir}/hypr/lib/hey.meta.lua
    '';

    home.configFile = {
      "hypr/hyprland.lua".text = ''
        -- Auto-generated by nixos
        package.path = "${hey.configDir}/hypr/?.lua;" .. package.path

        -- Generated from $XDG_DATA_HOME/hey/info.json
        hey = ${generators.toLua { multiline = true; indent = "  "; } config.hey.info}

        -- hey.hypr.monitors comes from modules.hyprland.monitors
        for _, m in ipairs(hey.hypr.monitors) do
          hl.monitor({
            output = m.output,
            mode = m.mode,
            position = m.position,
            scale = m.scale,
            disabled = m.disabled,
            vrr = m.vrr
          })
        end

        if hey.hypr.primaryMonitor then
          hl.on("hyprland.start", function ()
            -- Wayland has no concept of a primary monitor, so XWayland windows may
            -- start in unpredictable places without this hint.
            hl.exec_cmd("${pkgs.xrandr}/bin/xrandr --output " .. hey.hypr.primaryMonitor .. " --primary")
          end)
        end

        hl.on("hyprland.start", function ()
          hl.exec_cmd("hey hook onStartup")
        end)

        require("hyprland")
        pcall(require, "hyprland-post")
        pcall(require, "${matugenModule}")  -- generated by matugen
      '';

      "hypr/hyprland-post.lua" = mkIf (cfg.extraConfig != "") {
        text = cfg.extraConfig;
      };
    };
  };
}
