## modules/hyprland/default.nix
#
# Sets up a hyprland-based desktop environment.

{ hey, heyBin, lib, config, pkgs, ... }:

with lib;
with hey.lib;
let cfg = config.modules.hyprland;
in {
  options.modules.hyprland = with types; {
    enable = mkBoolOpt false;
    extraConfig = mkOpt lines "";
    plugins = mkOpt (listOf package) [];
    monitors = mkOpt (listOf (submodule {
      options = {
        output = mkOpt str "";
        mode = mkOpt str "preferred";
        position = mkOpt str "auto";
        scale = mkOpt int 1;
        disabled = mkOpt bool false;
        primary = mkOpt bool false;
        vrr = mkOpt int 0;
      };
    })) [{}];
  };

  config = mkIf cfg.enable (mkMerge [
    ## The compositor.
    (let flake = hey.inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system};
     in {
      hey.desktop = "hyprland";

      programs.hyprland = {
        enable = true;
        withUWSM = true;
        systemd.setPath.enable = true;
        package = flake.hyprland;
        portalPackage = flake.xdg-desktop-portal-hyprland;
      };

      # Niri-style overview. Nothing caches this one, so every hyprland bump
      # buys a two-minute compile.
      modules.hyprland.plugins = [
        hey.inputs.scroll-overview.packages.${pkgs.stdenv.hostPlatform.system}.scrolloverview
      ];

      nix.settings = {
        substituters = [ "https://hyprland.cachix.org" ];
        trusted-public-keys = [ "hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc=" ];
      };

      environment.sessionVariables = {
        ELECTRON_OZONE_PLATFORM_HINT = "auto";
        NIXOS_OZONE_WL = "1";
        MOZ_ENABLE_WAYLAND = "1";
      };
    })

    ## Its config: config/hypr/, entered through a generated hyprland.lua.
    (let primaryMonitor = findFirst (x: x.primary) {} cfg.monitors;
         colorsModule = "hyprland-colors";
     in {
      # The name is all config/hypr/ and Noctalia get, and "" is truthy in Lua:
      # it would name a monitor that doesn't exist rather than read as absent.
      assertions = [{
        assertion = !(primaryMonitor ? output && primaryMonitor.output == "");
        message = "modules.hyprland.monitors: the primary monitor needs an `output`.";
      }];

      hey.info.hypr = {
        primaryMonitor = primaryMonitor.output or null;
        monitors = cfg.monitors;
        # config/hypr/hyprland.lua gates gesture features on this. hl.version()
        # is no use for a git build: it reports whatever VERSION says on main,
        # which lags the releases.
        version = config.programs.hyprland.package.version;
      };

      home.configFile."hypr/hyprland.lua".text = ''
        -- Auto-generated by nixos
        package.path = "${hey.configDir}/hypr/?.lua;" .. package.path

        -- Generated from $XDG_DATA_HOME/hey/info.json
        hey = ${generators.toLua { multiline = true; indent = "  "; } config.hey.info}

        -- hey.hypr.monitors comes from modules.hyprland.monitors
        for _, m in ipairs(hey.hypr.monitors) do
          hl.monitor({
            output = m.output,
            mode = m.mode,
            position = m.position,
            scale = m.scale,
            disabled = m.disabled,
            vrr = m.vrr
          })
        end

        if hey.hypr.primaryMonitor then
          hl.on("hyprland.start", function ()
            -- Wayland has no concept of a primary monitor, so XWayland windows may
            -- start in unpredictable places without this hint.
            hl.exec_cmd("${pkgs.xrandr}/bin/xrandr --output " .. hey.hypr.primaryMonitor .. " --primary")
          end)
        end

        -- Before config/hypr/, which reaches for hl.plugin.*. A plugin can only
        -- be loaded once per session, so this is a restart, not a `hey reload`.
        ${concatMapStringsSep "\n"
            (p: ''hl.plugin.load("${p}/lib/lib${p.pname}.so")'') cfg.plugins}

        require("hyprland")
        pcall(require, "hyprland-post")
        pcall(require, "${colorsModule}")  -- rendered by Noctalia (see theme.nix)
      '';

      home.configFile."hypr/hyprland-post.lua" = mkIf (cfg.extraConfig != "") {
        text = cfg.extraConfig;
      };

      modules.hyprland.theme.templates.hyprland = {
        input_path = "${hey.configDir}/hypr/hyprland-colors.template.lua";
        output_path = "${config.home.configDir}/hypr/${colorsModule}.lua";
      };

      modules.shell.zsh.rcFiles = [ "${hey.configDir}/hypr/aliases.zsh" ];
    })

    ## So lua-language-server completion and linting is aware of hyprland's API,
    ## and of the hey table this module splices in beside it. Both are gitignored
    ## by .gitignore's *.meta.lua.
    (let
      # Describe the `hey` table for `lua-language-server` dynamically, so the two
      # can't drift. Nested classes must come first.
      luaMeta = name: attrs: bind:
        let
          typeOf = path: v:
                 if v == null  then "any"  # says a field exists, not what it holds
            else if isBool v   then "boolean"
            else if isInt v    then "integer"
            else if isString v then "string"
            else if isAttrs v  then path
            else if isList v   then (if v == [] then "any[]" else "${typeOf path (head v)}[]")
            else "number";
          # A list documents its element type, so both spell the same class
          # name -- and typeOf recurses through nesting, so this has to too, or
          # a list of lists of attrs names a class nothing defines.
          elemOf = v: if isList v && v != [] then elemOf (head v) else v;
          nested = concatMap
            (n: let path = "${name}.${n}"; in
                optionals (isAttrs (elemOf attrs.${n}))
                  (luaMeta path (elemOf attrs.${n})
                           "local ${replaceStrings ["."] ["_"] "__${path}"}"))
            (attrNames attrs);
        in nested ++ [ ''
          ---@class ${name}
          ${concatMapStringsSep "\n"
              (n: "---@field ${n} ${typeOf "${name}.${n}" attrs.${n}}")
              (attrNames attrs)}
          ${bind} = {}
        '' ];

      heyMeta = pkgs.writeText "hey.meta.lua" ''
        -- Auto-generated by nixos, from hey.info. Describes the `hey` table that
        -- modules/hyprland/default.nix splices into hyprland.lua.
        ---@meta

        ${concatStringsSep "\n" (luaMeta "hey" config.hey.info "hey")}
      '';
    in {
      system.userActivationScripts.hyprlandLuaStub = ''
        ln -sfn ${config.programs.hyprland.package}/share/hypr/stubs/hl.meta.lua \
                ${hey.configDir}/hypr/lib/hl.meta.lua
        ln -sfn ${heyMeta} ${hey.configDir}/hypr/lib/hey.meta.lua
      '';
    })

    ## For CLIs
    {
      environment.systemPackages = with pkgs; [
        wlr-randr      # for monitors that hyprctl can't handle
        wf-recorder    # for screencasting
        quickshell     # for screencast's region indicator
        slurp          # slop
        grim           # screenshot
        ripdrag        # Replaces xdragon
        wev            # Replaces xev
        wl-clipboard   # Replaces xclip
        wtype          # Replaces xdotool (sorta)
        swayimg        # Replaces feh (as an image previewer)
        imv
        libnotify      # notify-send
        xdg-utils
        sox            # for `play` utility
        hyprpicker     # replaces `dms color pick`
      ];

      # To give Rofi targets
      user.packages = map (fmt:
        mkLauncherEntry "Color picker: grab ${fmt} at point" {
          icon = "com.github.finefindus.eyedropper";
          exec = "hyprpicker -a -f ${toLower fmt}";
        }) [ "RGB" "HSL" "hex" ];

      home.configFile.swayimg = {
        source = "${hey.configDir}/swayimg";
        recursive = true;
      };
    }

    ## The session's edges.
    {
      # Whoever asks for the shutdown fires on-shutting-down itself and waits on
      # it -- Noctalia's power menu through its hooks table (./noctalia.nix),
      # config/rofi/bin/powermenu.zsh by hand -- so the fade and the sound
      # finish before systemd is told anything. This is for everything else: a
      # bare `systemctl poweroff`, an ssh `reboot`, a critical battery. Stopping
      # last means the compositor and pipewire are still up to serve the fade,
      # and on-shutting-down.zsh's stamp keeps the second call quiet when an
      # eager caller got there first.
      systemd.user.services.hey-shutdown-hook = {
        description = "Run hey's shutdown hooks before the session dies";
        wantedBy = [ "graphical-session.target" ];
        partOf = [ "graphical-session.target" ];
        after = [
          "graphical-session.target"
          "wayland-wm@hyprland.desktop.service"  # the compositor, for the fade
          "noctalia.service"                     # the toast
          "pipewire.service"                     # the sound; sox goes out
          "pipewire-pulse.service"               # through the pulse shim
        ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStart = "${getExe' pkgs.coreutils "true"}";
          # -f because the stamp is the guard now; hook.janet's would only make
          # a no-op exit 127 and log a unit failure on the way down.
          ExecStop = "${heyBin} hook -f on-shutting-down";
          # A wedged hook must not hold the shutdown open indefinitely.
          TimeoutStopSec = 15;
        };
      };

      # Noctalia has no suspend/resume events, so these ride systemd's sleep
      # target instead. They run as root; --machine=USER@.host --user is how
      # root reaches into the user's session without sudo, and `|| true` is so a
      # failing hook can't fail the unit.
      #
      # Not powerManagement.{powerDown,resume}Commands, which would be the
      # obvious home: nixpkgs pastes powerDownCommands into post-boot's preStop
      # as well as sleep-actions', so everything put there also fires on every
      # poweroff -- the sleep sound on the way down, over the shutdown one.
      systemd.services.hey-sleep-hook =
        let run = hook: ''
              ${pkgs.systemd}/bin/systemd-run --machine=${config.user.name}@.host \
                --user --pipe --wait --collect --quiet \
                ${heyBin} hook -f ${hook} || true
            '';
        in {
          description = "Run hey's sleep hooks around suspend";
          wantedBy = [ "sleep.target" ];
          before = [ "sleep.target" ];
          # So resuming stops the unit, and stopping it is what runs on-wakeup.
          unitConfig.StopWhenUnneeded = true;
          script = run "on-suspend";
          preStop = run "on-wakeup";
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            # systemd-run --wait blocks; a wedged hook must not hold the lid.
            TimeoutStartSec = 15;
            TimeoutStopSec = 15;
          };
        };
    }
  ]);
}
