#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew install weechat
        ;;
    linux*)
        if [[ -d /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S weechat
        elif [[ -d /etc/debian_version ]]; then
            # TODO Untested
            sudo apt-get install -y weechat
        fi
esac

# NOTE: init.sh needs to be run separately, afterward
echo "Don't forget to run weechat/scripts/init.sh while weechat is open"
