#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew install node
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S nodejs npm
        fi
        ;;
esac
