#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew cask install virtualbox
        brew install docker docker-compose docker-machine
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S docker docker-compose
        fi
esac
