name: NixOS

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'GNOME.md'
      - 'README.md'
      - 'notes/**'
      - '.git-crypt/**'
      - '.gitattributes'
      - '.gitignore'
      - 'home/**'
      - 'outputs/home-conf.nix'
      - 'outputs/installation.nix'
      - 'build'
      - 'switch'

jobs:
  build-ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v15

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v10
        with:
          name: jamesmstonenixos
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Check NixOS config ❄️"
        run: ./bin/hey check

      - name: "Rebuild NixOS config ❄️"
        run: ./bin/hey rebuild

  build-iso:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v15

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v10
        with:
          name: jamesmstonenixos
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Build NixOS iso ❄️"
        run: ./build iso-system
