#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew install cabal-install ghc
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S cabal-install ghc
        fi
        ;;
esac

cabal update
cabal install happy haskell-src-exts
