#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew install cabal-install ghc
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            pacaur --needed --noconfirm -S stack ncurses5-compat-lib
            stack setup
        fi
        ;;
esac

cabal update
cabal install happy haskell-src-exts
