#!/usr/bin/env bash

case $OSTYPE in
    darwin*)
        brew install ghc cabal-install
        ;;
    linux*)
        if [[ -f /etc/arch-release ]]; then
            sudo pacman --needed --noconfirm -S ghc cabal-install
        fi
        ;;
esac
